version: "3.8"

services:
  
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: expense_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
  
  metabase:
    image: metabase/metabase
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: expense_db
      MB_DB_PORT: 5432
      MB_DB_USER: root
      MB_DB_PASS: root
      MB_DB_HOST: postgres
    depends_on:
      postgres:
        condition: service_healthy

  etl:
    build: .
    depends_on:
      - postgres
    environment:
      - PGUSER=root
      - PGPASSWORD=root
      - PGDATABASE=expense_db
      - PGHOST=postgres
      - PGPORT=5432
    volumes:
      - ./statements:/app/statements
      - ./cache:/app/.cache
      - .:/app
    command: python etl_pipeline.py
    restart: "no"

volumes:
  pgdata:
